"use strict";

/**
 * Phase 12 — deliverable file storage.
 *
 * Storage is deliberately a *service* with a driver boundary so the
 * deliverable controller never knows where bytes live (Controller → Deliverable
 * service → Storage service → provider, §13). The local driver is the default
 * for development; `UPLOAD_DRIVER=s3` documents the extension point for a real
 * object store without pulling in a provider SDK we don't use yet.
 *
 * Security rules that live here, not in the controller (§16):
 *   - the storage key is generated by us; the client filename never becomes a
 *     path segment (no traversal, no overwrite of another version's file)
 *   - the stored name is sanitized to a safe basename for display/download
 *   - files are never served statically; they are streamed through an
 *     authorized endpoint, so no filesystem path or credential is exposed
 *   - the declared MIME type is checked against a policy allowlist *and*
 *     cross-checked against the file's magic bytes, because both the browser
 *     and the client can lie about either one
 */

const crypto = require("crypto");
const fs = require("fs");
const fsp = require("fs/promises");
const path = require("path");
const { ApiError } = require("../middleware/errorHandler");

const DEFAULT_UPLOAD_DIR = path.join(__dirname, "..", "..", "uploads");
const DEFAULT_MAX_FILE_SIZE = 10 * 1024 * 1024; // 10 MB

/**
 * Allowed deliverable types (§15). Configurable through
 * DELIVERABLE_ALLOWED_MIME_TYPES so a deployment can tighten or widen the
 * policy without a code change. Values are exact MIME types; no wildcards, so
 * an allowlist can never accidentally match `text/html`.
 */
const DEFAULT_ALLOWED_MIME_TYPES = [
  // Documents
  "application/pdf",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.ms-powerpoint",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "text/plain",
  "text/csv",
  "text/markdown",
  // Images
  "image/png",
  "image/jpeg",
  "image/gif",
  "image/webp",
  // Archives
  "application/zip",
  "application/gzip",
  "application/x-tar",
];

// Magic-byte signatures for the formats where sniffing is decisive. A format
// not listed here is still accepted, but only on its declared type — we never
// guess, and we never accept a type whose signature contradicts the bytes.
const SIGNATURES = [
  { mime: "application/pdf", bytes: [0x25, 0x50, 0x44, 0x46] }, // %PDF
  { mime: "image/png", bytes: [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a] },
  { mime: "image/jpeg", bytes: [0xff, 0xd8, 0xff] },
  { mime: "image/gif", bytes: [0x47, 0x49, 0x46, 0x38] },
  { mime: "application/zip", bytes: [0x50, 0x4b, 0x03, 0x04] },
  { mime: "application/gzip", bytes: [0x1f, 0x8b] },
  { mime: "application/x-tar", bytes: [0x75, 0x73, 0x74, 0x61, 0x72] }, // "ustar" at 257
];

// ZIP-container formats: the OOXML family and plain zip share the PK header,
// so a .docx is a zip container and must sniff as one.
const ZIP_CONTAINER_MIME_TYPES = new Set([
  "application/zip",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
]);

// Legacy OLE compound documents (doc/xls/ppt) share the D0 CF 11 E0 header.
// Types with no magic bytes: plain text formats, verified by policy rather
// than by signature.
const SIGNATURE_FREE_MIME_TYPES = new Set([
  "text/plain",
  "text/csv",
  "text/markdown",
  "text/html",
  "application/json",
]);

const OLE_MIME_TYPES = new Set([
  "application/msword",
  "application/vnd.ms-excel",
  "application/vnd.ms-powerpoint",
]);

const EXTENSION_BY_MIME = {
  "application/pdf": ".pdf",
  "application/msword": ".doc",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ".docx",
  "application/vnd.ms-excel": ".xls",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ".xlsx",
  "application/vnd.ms-powerpoint": ".ppt",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": ".pptx",
  "text/plain": ".txt",
  "text/csv": ".csv",
  "text/markdown": ".md",
  "image/png": ".png",
  "image/jpeg": ".jpg",
  "image/gif": ".gif",
  "image/webp": ".webp",
  "application/zip": ".zip",
  "application/gzip": ".gz",
  "application/x-tar": ".tar",
};

function getUploadDir() {
  return path.resolve(process.env.UPLOAD_DIR || DEFAULT_UPLOAD_DIR);
}

function getMaxFileSize() {
  const raw = Number(process.env.DELIVERABLE_MAX_FILE_SIZE);
  return Number.isFinite(raw) && raw > 0 ? raw : DEFAULT_MAX_FILE_SIZE;
}

function getAllowedMimeTypes() {
  const raw = process.env.DELIVERABLE_ALLOWED_MIME_TYPES;
  if (!raw) return [...DEFAULT_ALLOWED_MIME_TYPES];
  const parsed = raw
    .split(",")
    .map((v) => v.trim().toLowerCase())
    .filter(Boolean);
  return parsed.length ? parsed : [...DEFAULT_ALLOWED_MIME_TYPES];
}

/**
 * Reduce an arbitrary client filename to a safe basename: strip any directory
 * components (including Windows separators and traversal attempts), drop
 * control characters, and keep a conservative character set.
 */
function sanitizeFileName(originalName) {
  const raw = String(originalName || "").trim();
  const base = raw.split(/[\\/]/).pop() || "upload";
  const cleaned = base
    .replace(/[\u0000-\u001f\u007f]/g, "")
    .replace(/[^A-Za-z0-9._-]+/g, "_")
    .replace(/^\.+/, "")
    .slice(0, 120);
  return cleaned || "upload";
}

function detectSignature(buffer) {
  if (!buffer || buffer.length < 4) return null;

  for (const signature of SIGNATURES) {
    if (signature.bytes.every((byte, index) => buffer[index] === byte)) {
      return signature.mime;
    }
  }

  // RIFF....WEBP
  if (
    buffer.length >= 12 &&
    buffer.toString("ascii", 0, 4) === "RIFF" &&
    buffer.toString("ascii", 8, 12) === "WEBP"
  ) {
    return "image/webp";
  }

  // Legacy OLE compound document (doc/xls/ppt)
  if (buffer.length >= 8 && buffer.readUInt32LE(0) === 0xe011cfd0) {
    return "ole";
  }

  return null;
}

/**
 * Validate an uploaded file against the policy: non-empty, within the size
 * limit, an allowed MIME type, and — where the format has a signature — bytes
 * that agree with the declared type. Throws 400 ApiError with a message safe
 * to show the user.
 */
function validateUpload(file) {
  if (!file || !file.buffer || !file.buffer.length) {
    throw new ApiError(400, "A deliverable file is required");
  }

  const maxSize = getMaxFileSize();
  if (file.buffer.length > maxSize) {
    const mb = (maxSize / (1024 * 1024)).toFixed(1);
    throw new ApiError(400, `File is too large (maximum ${mb} MB)`);
  }

  const declared = String(file.mimetype || "").toLowerCase().split(";")[0].trim();
  const allowed = getAllowedMimeTypes();
  if (!declared || !allowed.includes(declared)) {
    throw new ApiError(400, "Unsupported file type");
  }

  // Content verification. Formats that carry a signature must present one:
  // a text file renamed to `.pdf` has no signature, and accepting it would
  // make the allowlist meaningless. Text formats have no signature to find,
  // so they are exempt — they are also the only types here that cannot be
  // polyglot in a way that matters.
  const signature = detectSignature(file.buffer);
  if (signature) {
    const compatible =
      signature === declared ||
      (signature === "application/zip" && ZIP_CONTAINER_MIME_TYPES.has(declared)) ||
      (signature === "ole" && OLE_MIME_TYPES.has(declared));
    if (!compatible) {
      throw new ApiError(400, "File contents do not match the declared file type");
    }
  } else if (!SIGNATURE_FREE_MIME_TYPES.has(declared)) {
    throw new ApiError(400, "File contents do not match the declared file type");
  }

  return {
    mimeType: declared,
    fileSize: file.buffer.length,
    fileName: sanitizeFileName(file.originalname),
  };
}

function checksum(buffer) {
  return crypto.createHash("sha256").update(buffer).digest("hex");
}

/**
 * Build the storage key for a version's file. The version's identity and a
 * random token do the naming; the sanitized original name is only a readable
 * suffix, so two uploads of the same filename can never collide and a crafted
 * filename can never escape the deliverable's directory.
 */
function buildStorageKey({ workspaceId, projectId, deliverableId, versionNumber, fileName, mimeType }) {
  const token = crypto.randomBytes(8).toString("hex");
  const extension = path.extname(fileName) || EXTENSION_BY_MIME[mimeType] || "";
  return path.posix.join(
    "deliverables",
    String(workspaceId),
    String(projectId),
    String(deliverableId),
    `v${versionNumber}-${token}${extension}`
  );
}

function driver() {
  const name = String(process.env.UPLOAD_DRIVER || "local").toLowerCase();
  if (name !== "local") {
    // A provider adapter plugs in here. Failing loudly beats silently writing
    // to the wrong place.
    throw new ApiError(500, "Configured upload driver is not available");
  }
  return "local";
}

/**
 * Persist a validated upload. Returns the storage reference + metadata that
 * the version record stores; the bytes are addressed only by `storageKey`.
 */
async function saveUpload(file, { workspaceId, projectId, deliverableId, versionNumber }) {
  const validated = validateUpload(file);
  const storageKey = buildStorageKey({
    workspaceId,
    projectId,
    deliverableId,
    versionNumber,
    fileName: validated.fileName,
    mimeType: validated.mimeType,
  });

  const uploadDir = getUploadDir();
  const target = path.resolve(uploadDir, storageKey);

  // Belt and braces: even though storageKey is generated by us, refuse any
  // path that would land outside the upload root.
  if (target !== uploadDir && !target.startsWith(uploadDir + path.sep)) {
    throw new ApiError(400, "Invalid file path");
  }

  try {
    driver();
    await fsp.mkdir(path.dirname(target), { recursive: true });
    await fsp.writeFile(target, file.buffer, { flag: "wx" });
  } catch (error) {
    if (error instanceof ApiError) throw error;
    throw new ApiError(500, "Could not store the uploaded file");
  }

  return {
    storageKey,
    fileName: validated.fileName,
    fileSize: validated.fileSize,
    mimeType: validated.mimeType,
    checksum: checksum(file.buffer),
    fileUrl: `/api/deliverables/${deliverableId}/file/${storageKey.split("/").pop()}`,
  };
}

/**
 * Open a stored file for streaming. `storageKey` comes from the database, but
 * it is still resolved and re-checked against the upload root so a corrupted
 * or hand-edited record cannot turn the download route into a file reader.
 */
async function openStoredFile(storageKey) {
  const uploadDir = getUploadDir();
  const target = path.resolve(uploadDir, String(storageKey || ""));

  if (!target.startsWith(uploadDir + path.sep)) {
    throw new ApiError(404, "File not found");
  }

  try {
    const stat = await fsp.stat(target);
    if (!stat.isFile()) throw new Error("not a file");
    return { path: target, size: stat.size, stream: fs.createReadStream(target) };
  } catch {
    throw new ApiError(404, "File not found");
  }
}

async function removeStoredFile(storageKey) {
  if (!storageKey) return;
  const uploadDir = getUploadDir();
  const target = path.resolve(uploadDir, String(storageKey));
  if (!target.startsWith(uploadDir + path.sep)) return;
  await fsp.rm(target, { force: true });
}

module.exports = {
  DEFAULT_MAX_FILE_SIZE,
  DEFAULT_ALLOWED_MIME_TYPES,
  buildStorageKey,
  checksum,
  detectSignature,
  getAllowedMimeTypes,
  getMaxFileSize,
  getUploadDir,
  openStoredFile,
  removeStoredFile,
  sanitizeFileName,
  saveUpload,
  validateUpload,
};
