"use strict";

/**
 * The Socket.IO instance, the room naming convention, and the in-memory
 * presence table — the three things both the REST layer and the socket
 * handlers need to agree on.
 *
 * Nothing here talks to the database or emits an event on its own behalf;
 * see `emit.js` for the broadcast helpers and `presence.js` for the
 * reference counting.
 */

let io = null;

function setIO(instance) {
  io = instance;
}

function getIO() {
  return io;
}

// ---------------------------------------------------------------------------
// Room naming
//
// One convention, shared by every emitter and every join handler, so a room
// can never be spelled two different ways.
// ---------------------------------------------------------------------------

/** Private per-user room. Only reachable by sockets that authenticated as that user. */
const userRoom = (userId) => `user:${String(userId)}`;

/** Project-scoped room. Every task/column/comment/deliverable event goes here. */
const projectRoom = (projectId) => `project:${String(projectId)}`;

/** Workspace-scoped room, used for presence. */
const workspaceRoom = (workspaceId) => `workspace:${String(workspaceId)}`;

/**
 * Shared channel room.
 *
 * A channel's `_id` is generated by Mongo and is unique across every workspace
 * in the system, so it is the room name on its own — no workspace segment is
 * needed, and the frontend can subscribe with nothing but the channel id it
 * already has from `GET /channels`.
 *
 * Channels are *not* direct messages. Those are delivered only to the two
 * participants' `user:<id>` rooms and never occupy a room like this one.
 */
const channelRoom = (channelId) => `channel:${String(channelId)}`;

/**
 * @deprecated Retained for the existing call sites that predate Phase 18. The
 * project room is the same room — `board:<id>` was always a project-scoped
 * room, it just had a narrower name.
 */
const boardRoom = projectRoom;

module.exports = {
  setIO,
  getIO,
  userRoom,
  projectRoom,
  workspaceRoom,
  channelRoom,
  boardRoom,
};
